### PR TITLE
Amanda LESS Refactor

### PR DESCRIPTION
**Pull request by phillipsdev**
# Description

Please include a summary of the change and a link to which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

LESS refactor
One central command for the compiler now as everything is imported into one less file which is index.less. Then gets compiled into the index.css. The command needed is: 
`less-watch-compiler less css index.less`
Please do not compile any other file. If another file is created all you would need to do is import it in the index.less.

There is a variables.less that houses all the variables that should be used. (Honestly there's probably more than we should be using) So any color should be a variable.

There is a mixins file, this is not feature complete, there can be more added, and I probably missed a few to actually mixin that I created.

There is a global.less file that should house all global styles that will affect the entire project and can be used in any component.

Also removed unnecessary files that weren't being used anymore.

Please delete options that are not relevant.

- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Styles! Viewed in browser to ensure consistency.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My code has been reviewed by at least one peer
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by phillipsdev** [comment]
Found the missing kinks I believe. If anything is missing let me know!

**Review by iqra-javed — COMMENTED** [review]
Great job on organizing the less files Amanda. I did notice some slight variation in styles between this branch and the master. Please have a look: 
                                                                                                              
**Landing Page:** 
-cancel button should be red on sign in and sign up modal (it should be red across the app)
-forgot password button should be grey on sign in modal

**Calendar Page:**
-footer looks off (maybe because the main container height didnt transfer over?)
-main background color should be blue gradient
-background for calendar events looks like a brighter red?
-hover effects are missing for buttons on scheduling modal and checkoff performance modal
-cancel button should be red
-scheduling modal dropdown should be centered

**Progress Page:**
-update progress button should be blue
-progress cards should be blue
-cancel button should be red

**Comment by phillipsdev** [comment]
Most of the button changes were on purpose. At least the cancel buttons. I made it consistent throughout the app to have all the cancel buttons grey. And so for the sign in the forgot password was changed to red. 

The events are a brighter red, that is our primary color. It was commented on in our UI session Friday that they needed to pop more. Also I took out many extra colors that were being used and used the main colors of our app. ( We are also going to have to do something about our gradients- that was commented on as well) Once again, for the buttons, hover effects were taken off on purpose. 

On the progress page - buttons were changed on purpose. However for the progress cards, the code actually was set to the red color in master it just didn't write that way which it why it showed up as red in my code. .I have however fixed it to be blue now.

Working on the footer, scheduling modal centering issue, and background of calendarPage body 👍

**Review by iqra-javed — APPROVED** [review]
Excellent work Amanda!

**Review by emukupa — APPROVED** [review]
nice work!!

**Pull request merged**
