### PR TITLE
Iqra vertical scroll fix

### PR DESCRIPTION
**Pull request by iqra-javed**
# Description

Please include a summary of the change and a link to which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change
- brought back the vertical scroll bar
- fixed minor styling inconsistencies on progress page

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

tested locally

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [x] My code has been reviewed by at least one peer
- [X] My changes generate no new warnings

### CODE REVIEW

**Review by rusticlion — APPROVED** [review]
Glitch is repaired on my local. We can remove the commented-out code this afternoon when we have our "cleanup" mob programming session.

**Comment by rusticlion** [comment]
Amanda should test as well, since my machine did not exhibit the problem in the first place.

**Review by phillipsdev — APPROVED** [review]
Also works on my machine 👍

**Review by emukupa — APPROVED** [review]
great work

**Pull request merged**
